# Generated by Django 4.1.7 on 2023-03-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
